input:
  # Path to tracklist file, make sure the file is UTF-8
  # Format must be inl
  #   You can use softwares like foobar2k, etc... to get the tracklist
  tracklist_path: input/tracklist.txt

  # Path to lang file, make sure the file is UTF-8
  lang_path: input/lang.txt

  # Each line in lang file contains id or not
  lang_id: false

output:
  # Your output file path
  tracklist_path: output/tracklist.txt
