# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'dotenv', '~> 2.2', '>= 2.2.1'

group :test, :development do
  gem 'rspec', '~> 3.7'
end
